substitutions:
  _REGION: europe-west1
  _REPO: visiodoc-ms
  _SERVICE: jitsi-ms

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/visiodoc-prod/$_REPO/$_SERVICE:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/visiodoc-prod/$_REPO/$_SERVICE:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'replace'
      - 'cloudrun.yaml'
      - '--region=$_REGION'

images:
  - 'europe-west1-docker.pkg.dev/visiodoc-prod/$_REPO/$_SERVICE:latest'

options:
  logging: CLOUD_LOGGING_ONLY